version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_mvc
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "6033:6033"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

